# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestprodusepromotii():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testprodusepromotii(self):
    # Test name: test_produse&promotii
    # Step # | name | target | value
    # 1 | open | /ro/ | 
    self.driver.get("http://34.118.122.203/ro/")
    # 2 | setWindowSize | 1532x810 | 
    self.driver.set_window_size(1532, 810)
    # 3 | click | css=.logo | 
    self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
    # 4 | click | css=.banner > .img-fluid | 
    self.driver.find_element(By.CSS_SELECTOR, ".banner > .img-fluid").click()
    # 5 | click | linkText=Toate produsele noi | 
    self.driver.find_element(By.LINK_TEXT, "Toate produsele noi").click()
    element = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.CSS_SELECTOR, '.select-title'))
    # 6 | click | css=.select-title |
    element.click()

    container = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.CLASS_NAME, 'container'))
    # 7 | click | linkText=Data adaugarii, de la noi la vechi | 
    self.driver.find_element(By.LINK_TEXT, "Data adaugarii, de la noi la vechi").click()
    assert 'Data adaugarii, de la noi la vechi' in self.driver.page_source

if __name__ == '__main__':
      pytest.main()

