# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsolicitareretur():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsolicitareretur(self):
    # Test name: test_solicitare_retur
    # Step # | name | target | value
    # 1 | open | /ro/ | 
    self.driver.get("http://34.118.122.203/ro/")
    # 2 | setWindowSize | 1532x810 | 
    self.driver.set_window_size(1532, 810)
    # 3 | click | linkText=Contacteaza-ne | 
    self.driver.find_element(By.LINK_TEXT, "Contacteaza-ne").click()
    # 4 | click | id=id_contact | 
    self.driver.find_element(By.ID, "id_contact").click()
    # 5 | select | id=id_contact | label=Reclamatie
    dropdown = self.driver.find_element(By.ID, "id_contact")
    dropdown.find_element(By.XPATH, "//option[. = 'Reclamatie']").click()
    # 6 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 7 | type | id=email | paula.cucu@yahoo.ro
    self.driver.find_element(By.ID, "email").send_keys("paula.cucu@yahoo.ro")
    # 8 | click | id=contactform-message | 
    self.driver.find_element(By.ID, "contactform-message").click()
    # 9 | click | id=contactform-message | 
    self.driver.find_element(By.ID, "contactform-message").click()
    # 10 | type | id=contactform-message | solicitare de returnare produs defect
    self.driver.find_element(By.ID, "contactform-message").send_keys("solicitare de returnare produs defect")
    # 11 | click | name=submitMessage | 
    self.driver.find_element(By.NAME, "submitMessage").click()
    # 12 | click | css=.alert | 
    self.driver.find_element(By.CSS_SELECTOR, ".alert").click()
    assert 'Mesajul tau a fost trimis catre echipa noastra.' in self.driver.page_source

if __name__ == '__main__':
    pytest.main()