# Generated by Selenium IDE
from telnetlib import EC

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtocart(self):
    # Test name: add_to_cart
    # Step # | name | target | value
    # 1 | open | /en/ | 
    self.driver.get("http://34.118.122.203/en/")
    # 2 | setWindowSize | 1536x835 | 
    self.driver.set_window_size(1536, 835)
    # 3 | click | css=.featured-products:nth-child(2) .js-product:nth-child(1) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".featured-products:nth-child(2) .js-product:nth-child(1) img").click()
    product_title = self.driver.find_element(By.CLASS_NAME,'h1').get_attribute('innerText')
    # 4 | click | css=.add-to-cart | 
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    element = WebDriverWait(self.driver,15).until(lambda d:d.find_element(By.CSS_SELECTOR,'.cart-content-btn > .btn-primary'))
    # 5 | click | css=.cart-content-btn > .btn-primary | 
    element.click()

    cart_container = WebDriverWait(self.driver, 15).until(lambda d: d.find_element(By.CLASS_NAME, 'cart-container'))
    assert product_title.lower() in self.driver.page_source.lower()

