# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsolicitareinformatiiinlocuireprodus():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsolicitareinformatiiinlocuireprodus(self):
    # Test name: test_solicitare_informatii_inlocuire_produs
    # Step # | name | target | value
    # 1 | open | /ro/ | 
    self.driver.get("http://34.118.122.203/ro/")
    # 2 | setWindowSize | 1532x810 | 
    self.driver.set_window_size(1532, 810)
    # 3 | click | linkText=Contacteaza-ne | 
    self.driver.find_element(By.LINK_TEXT, "Contacteaza-ne").click()
    # 4 | click | id=id_contact | 
    self.driver.find_element(By.ID, "id_contact").click()
    # 5 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 6 | type | id=email | paula.cucu@yahoo.ro
    self.driver.find_element(By.ID, "email").send_keys("paula.cucu@yahoo.ro")
    # 7 | click | css=.bootstrap-filestyle > .form-control | 
    self.driver.find_element(By.CSS_SELECTOR, ".bootstrap-filestyle > .form-control").click()
    # 1 | open | /administration/ |
    # 8 | click | id=contactform-message | 
    self.driver.find_element(By.ID, "contactform-message").click()
    # 9 | click | id=contactform-message |
    # 19 | type | id=contactform-message | Buna ziua ! Va rog sa ma informati care sunt pasii de urmat cu privire la inlocuirea unui produs defect. Va multumesc !
    self.driver.find_element(By.ID, "contactform-message").send_keys("Buna ziua ! Va rog sa ma informati care sunt pasii de urmat cu privire la inlocuirea unui produs defect. Va multumesc !")
    # 20 | click | name=submitMessage | 
    self.driver.find_element(By.NAME, "submitMessage").click()
    self.driver.get("http://34.118.122.203/administration/")
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | user@example.com
    self.driver.find_element(By.ID, "email").send_keys("user@example.com")
    # 5 | click | id=passwd |
    self.driver.find_element(By.ID, "passwd").click()
    # 6 | type | id=passwd | VTR6WmtBCvnZ
    self.driver.find_element(By.ID, "passwd").send_keys("VTR6WmtBCvnZ")
    # 7 | click | css=.ladda-label |
    self.driver.find_element(By.CSS_SELECTOR, ".ladda-label").click()
    tab = WebDriverWait (self.driver,15).until(lambda  d: d.find_element(By.CSS_SELECTOR, "#subtab-AdminParentCustomerThreads span"))
    tab.click()
    # 30 | click | linkText=Asistenta pentru clienti |
    subtab = WebDriverWait(self.driver, 10).until(lambda s: s.find_element(By.LINK_TEXT, "Customer Service"))
    subtab.click()
    # self.driver.find_element(By.LINK_TEXT, "Asistenta pentru clienti").click()
    # 31 | click | css=#box-pending-messages .title |
    self.driver.find_element(By.CSS_SELECTOR, "#box-pending-messages .title").click()
    # 32 | click | css=.odd > .column-email |
    self.driver.find_element(By.CSS_SELECTOR, ".odd > .column-email").click()
    # 33 | click | css=.message-item-initial-body |
    self.driver.find_element(By.CSS_SELECTOR, ".message-item-initial-body").click()
    # 34 | click | id=reply_message |
    self.driver.find_element(By.ID, "reply_message").click()
    # 35 | click | id=reply_message |
    self.driver.find_element(By.ID, "reply_message").click()
    # 36 | click | id=reply_message |
    self.driver.find_element(By.ID, "reply_message").click()
    # 37 | click | name=setstatus |
    # self.driver.find_element(By.NAME, "setstatus").click()
    # 38 | click | id=reply_message |
    # 49 | type | id=reply_message | Dear Customer,\nVa vom contacta, in cel mai scurt timp posibil . \n\nRegards,\nCustomer service
    self.driver.find_element(By.ID, "reply_message").send_keys("Dear Customer,\\nVa vom contacta, in cel mai scurt timp posibil . \\n\\nRegards,\\nCustomer service")
    # 50 | click | name=submitReply |
    self.driver.find_element(By.NAME, "submitReply").click()

